#!/usr/bin/env bash
STATUS=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
toggle() {
    if [ $STATUS == "no" ]; then
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
        notify-send --icon=volume-level-muted --urgency=normal "Microphone " "Microphone has been muted!"
    else
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
        notify-send --icon=volume-level-high --urgency=normal "Microphone" "Microphone has been unmuted!"
    fi
}

icon() {
    if [ $STATUS == "no" ]; then
        echo "󰍬"
    else
        echo "󰍭"
    fi
}

status() {
    if [ $STATUS == "no" ]; then
        echo "On"
    else
        echo "Off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
