#!/usr/bin/env bash
STATUS=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
toggle() {
    if [ $STATUS == "no" ]; then
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        notify-send --icon=volume-level-muted --urgency=normal "Volume " "Volume has been muted!"
    else
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        notify-send --icon=volume-level-high --urgency=normal "Volume" "Volume has been unmuted!"
    fi
}

icon() {
    if [ $STATUS == "no" ]; then
        echo "󰕾"
    else
        echo "󰖁"
    fi
}

status() {
    if [ $STATUS == "no" ]; then
        echo "On"
    else
        echo "Off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
