#!/bin/bash

# Replace lat and long with yours
URL="https://api.open-meteo.com/v1/forecast?latitude=49.4914&longitude=7.8547&current_weather=true"
DATA=$(curl -s "$URL")

if [ $1 == "--temperature" ]; then
  TEMPERATURE=$(echo "$DATA" | jq -r '.current_weather.temperature')
  echo "$TEMPERATURE"
fi

if [ "$1" == "--icon" ]; then
  CODE=$(jq -r '.current_weather.weathercode' <<< "$DATA")
  IS_DAY=$(jq -r '.current_weather.is_day' <<< "$DATA")

  case "$IS_DAY" in
    "1")
      case "$CODE" in
        0)
          DESCRIPTION=""
          ;;
        1|2|3)
          DESCRIPTION=""
          ;;
        45|48)
          DESCRIPTION=""
          ;;
        51|53|55)
          DESCRIPTION=""
          ;;
        56|57)
          DESCRIPTION=""
          ;;
        61|63|65)
          DESCRIPTION=""
          ;;
        66|67)
          DESCRIPTION="󰙿"
          ;;
        71|73|75)
          DESCRIPTION="󰼶"
          ;;
        77)
          DESCRIPTION="󰖘"
          ;;
        80|81|82)
          DESCRIPTION="󰼳"
          ;;
        85|86)
          DESCRIPTION="󰼴"
          ;;
        95)
          DESCRIPTION="󰖓"
          ;;
        96|99)
          DESCRIPTION="󰙾"
          ;;
        *)
          DESCRIPTION="Unknown weather code (day)"
          ;;
      esac
      ;;
    "0")
      case "$CODE" in
        0)
          DESCRIPTION="󰖔"
          ;;
        1|2|3)
          DESCRIPTION=""
          ;;
        45|48)
          DESCRIPTION=""
          ;;
        51|53|55)
          DESCRIPTION=""
          ;;
        56|57)
          DESCRIPTION=""
          ;;
        61|63|65)
          DESCRIPTION=""
          ;;
        66|67)
          DESCRIPTION="󰙿"
          ;;
        71|73|75)
          DESCRIPTION="󰼶"
          ;;
        77)
          DESCRIPTION="󰖘"
          ;;
        80|81|82)
          DESCRIPTION=""
          ;;
        85|86)
          DESCRIPTION=""
          ;;
        95)
          DESCRIPTION="󰖓"
          ;;
        96|99)
          DESCRIPTION="󰙾"
          ;;
        *)
          DESCRIPTION="Unknown weather code (day)"
          ;;
      esac
      ;;
  esac

  echo "$DESCRIPTION"
fi

if [ "$1" == "--description" ]; then
  CODE=$(jq -r '.current_weather.weathercode' <<< "$DATA")
  IS_DAY=$(jq -r '.current_weather.is_day' <<< "$DATA")

  case "$CODE" in
    0)
      DESCRIPTION="Clear sky"
      ;;
    1)
      DESCRIPTION="Mainly clear, partly cloudy, and overcast"
      ;;
    2)
      DESCRIPTION="Partly cloudy"
      ;;
    3)
      DESCRIPTION="Overcast"
      ;;
    45|48)
      DESCRIPTION="Fog"
      ;;
    51)
      DESCRIPTION="Light Drizzle"
      ;;
    53)
      DESCRIPTION="Moderate drizzle"
      ;;
    55)
      DESCRIPTION="Dense drizzle"
      ;;
    56)
      DESCRIPTION="Ligh freezing drizzle"
      ;;
    57)
      DESCRIPTION="Dense freezing drizzle"
      ;;
    61|63|65)
      DESCRIPTION="Slight rain"
      ;;
    63)
      DESCRIPTION="Moderate rain"
      ;;
    65)
      DESCRIPTION="Heavy rain"
      ;;
    66)
      DESCRIPTION="Light freezing rain"
      ;;
    67)
      DESCRIPTION="Heavy freezing rain"
      ;;
    71)
      DESCRIPTION="Slight snow fall"
      ;;
    73)
      DESCRIPTION="Moderate snow fall"
      ;;
    75)
      DESCRIPTION="Heavy snow fall"
      ;;
    77)
      DESCRIPTION="Snow grains"
      ;;
    80)
      DESCRIPTION="Slight rain showers"
      ;;
    81)
      DESCRIPTION="Moderate rain showers"
      ;;
    82)
      DESCRIPTION="Violent rain showers"
      ;;
    85)
      DESCRIPTION="Slight snow showers"
      ;;
    86)
      DESCRIPTION="Heavy snow showers"
      ;;
    95)
      DESCRIPTION="Thunderstorm: Slight"
      ;;
    96|99)
      DESCRIPTION="Thunderstorm with slight hail"
      ;;
    99)
      DESCRIPTION="Thunderstorm with heavy hail"
    *)
      DESCRIPTION="Unknown weather code"
      ;;
  esac

  if [ "$IS_DAY" == "false" ]; then
    DESCRIPTION="$DESCRIPTION (night)"
  fi

  echo "$DESCRIPTION"
fi
